\documentclass[12pt,a4paper]{scrartcl}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{tikz}
%\usepackage{silence}
\usepackage{mdframed}
%\WarningFilter{mdframed}{You got a bad break}
\usepackage[colorinlistoftodos]{todonotes}
\usepackage{listings}
\usepackage{color}
\colorlet{exampcol}{blue!10}
\usepackage{multicol}
\usepackage{booktabs}

\usepackage{exercise}

\usepackage[autostyle, english = american]{csquotes}
\MakeOuterQuote{"}

\usepackage{hyperref}
\hypersetup{
    colorlinks,
    citecolor=black,
    filecolor=black,
    linkcolor=blue,
    urlcolor=black
}

\title{Exercises for statistical inference and stuff}
\date{\today}
\author{Timoth\'ee Bonnet}


\begin{document}


\maketitle

\tableofcontents
\ListOfExerciseInToc
\ExerciseLevelInToc{subsubsection}

\clearpage

\section{Understanding error structure}

\subsection{Broken experiments}

\begin{Exercise}[difficulty=1, title={A significant result?}]
We carry out a vaccine challenge experiment. There are three experimental groups (saline control / low vaccine dose / high vaccine dose), with 6 mice in each group. For each group all mice are housed together in the same cage (so there are three cages). All mice are challenged with \emph{Shigella}, their symptom intensity is scored on day 8. A one-way ANOVA identifies an effect of the treatment, and pair-wise Bonferroni tests show the low-dose to be statistically significant different from the two other groups:

\includegraphics[width=0.4\textwidth]{Figures/message1}

\textbf{What is suspicious in the result? What part of the design may explain the result? How to improve the design (there are at least two different ways)?}
\end{Exercise}


\begin{Exercise}[difficulty=1, title={A better experimental design}]
We study how a membrane protein intakes external molecules in frog eggs. The target molecules are radioactively labelled so we can measure intake. We created five mutant lines to test what part of the protein controls intake. We propose to measure six tubes of ten eggs every week. Each week we will test a different genotype (i.e., the control or one of the five mutants):

\includegraphics[width=0.8\textwidth]{Figures/expdes2}

\textbf{How much information about mutants can we extract from this experiment? How to improve the design?}

\end{Exercise}


\subsection{Broken models?}

Let's look at models with data from the an experiment similar to the mice example.
\begin{Exercise}[difficulty=1, title={lm vs. lmer vs. lm+}]

Load the dataset "challenge2.csv", and test the effect of the vaccine treatment ("Group") on the immune response ("Percent.loss"). 
First fit a fixed-effect only linear model and/or an anova. Is there a clear effect of treatment?\\
Now add a random effect for Cage (e.g., using the package lme4), what happens to the effect of treatment?\\
Finally, fit Cage and Group as fixed effects in a simple linear model and/or anova. What happens, why?\\
Which of the three models should you trust or not?

\end{Exercise}

<<echo=FALSE, eval=FALSE>>=
mice <- read.csv("Data/challenge2.csv")
library(lme4)
summary(lm(Percent.loss ~ 1 + Group, data=mice))
anova(lm(Percent.loss ~ 1 + Group, data=mice))

summary(lmer(Percent.loss ~ 1 + Group + (1|Cage), data=mice))
anova(lmer(Percent.loss ~ 1 + Group + (1|Cage), data=mice))

summary(lm(Percent.loss ~ 1 + Group + Cage, data=mice))
anova(lm(Percent.loss ~ 1 + Group + Cage, data=mice))
@


\section{Interpreting simple mixed models}



\section{Flexible variance structures}

<<echo=FALSE, eval=FALSE>>=
respi <- read.csv("Data/Prac4respiration data.csv")

@

\end{document}
